[versions]
#Application
packageName = "com.pointlessapps.mica"
minSdk = "26"
targetSdk = "36"

#Kotlin
kotlin = "2.2.21"
coroutines = "1.10.2"

#Android
gradlePlugin = "8.13.0"

#AndroidX
androidxCore = "1.17.0"

#Compose
composeCompiler = "1.5.15"
composeBom = "2025.11.00"
composeRuntime = "1.9.4"
composeMultiplatform = "1.9.2"

material = "1.13.0"

#Detekt
detekt = "1.23.8"
detektFormattingPlugin = "io.gitlab.arturbosch.detekt:detekt-formatting"

[libraries]
#Kotlin
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

#AndroidX
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }

#Compose
composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
composeUi = { module = "androidx.compose.ui:ui" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
composeMaterial = { module = "androidx.compose.material3:material3" }
composeViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose" }

material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
#Kotlin
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinComposeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }

#Android
application = { id = "com.android.application", version.ref = "gradlePlugin" }
library = { id = "com.android.library", version.ref = "gradlePlugin" }

#Detekt
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
